on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
permissions:
  contents: read

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
         -uses: ctions/checkout@v3
         -name: Set uo JDK 11
         uses: actions/setup-java@v3
         with:
            java-version: '11'
             distribution: 'temurin'
